### ISSUE TITLE
No donation link

### ISSUE THREAD

**Issue by GitAlbino** [marvinlehmann/Mouse-Debouncer#2]
Not technically an issue.

This little tool saves me from doing annoying and delicate mouse surgery or straight up buying a new mouse. This is a real relief so I wanted to leave a small donation to thank marvinlehmann but couldnt find a way to do so.

**Comment by marvinlehmann** [comment]
Hey, thank you in advance! =)
I hope your mouse stays tameable by this program. :)

https://www.paypal.com/donate/?hosted_button_id=MJQYP27WXXMML / https://www.paypal.me/marvinlehmann

**Comment by GitAlbino** [comment]
Hope you got that thing i sent you. Thanks again.

**Comment by marvinlehmann** [comment]
Yes, I got your donation. Thank you very much! =)
